class APP_CONSTANTS:
	CONFIG_FROM_ENV = 'YOURAPPLICATION_SETTINGS'

class DB_CONSTANTS:
	USER_COLLECTION = 'users'

class ALPHA_VANTAGE_URLS:
	BASE_URL = 'https://www.alphavantage.co/query'

	class FUNCTIONS:
		SYMBOL_SEARCH = 'SYMBOL_SEARCH'
		TIME_SERIES_INTRADAY = 'TIME_SERIES_INTRADAY'